webapp/mainte/models.py
from datetime import datetime
from webapp.app import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(db.Model, UserMixin):
    # テーブル名
    __tablename__ = "users"
    # カラム設定
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    # パスワードのプロパティ
    @property
    def password(self):
        raise AttributeError("読み取り不可です。")
    
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 入力したパスワードが正しいか判定する
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # emailが重複しているか判定する
    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None

# ログインしているユーザー情報を取得する
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

webapp/mainte/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import Length, DataRequired, Email

class UserForm(FlaskForm):
    username = StringField(
        label="ユーザー名",  
        validators=[
            DataRequired(message="ユーザー名を入力してください。"), 
            Length(max=15, message="ユーザー名を15文字以内で入力してください。"),
        ]
    )
        
    email = StringField(
        label="メールアドレス",
        validators=[
            DataRequired(message="メールアドレスを入力してください。"),
            Length(max=30, message="メールアドレスを30文字以内で入力してください。"),
            Email(message="メールアドレスが不正です。"),
        ]
    )

    password = PasswordField(
        label="パスワード",
        validators=[
            DataRequired(message="パスワードを入力してください。"),
            Length(max=15, message="パスワードを15文字以内で入力してください。"),
        ]
    )

    submit = SubmitField(
        label="新規登録"
    )

webapp/mainte/__init__.py
import webapp.mainte.models

webapp/mainte/views.py
from flask import Blueprint, current_app, render_template, redirect, url_for
from webapp.app import db
from webapp.mainte.models import User
from webapp.mainte.forms import UserForm

mainte = Blueprint("mainte", __name__, template_folder="templates", static_folder="static")

@mainte.route("/")
def index():
    # ログを出力する
    current_app.logger.debug("mainte.index start")
    return render_template("mainte/index.html")

# ユーザー一覧画面
@mainte.route("/users/")
def users_index():
    # ログを出力する
    current_app.logger.debug("mainte.users start")
    users = User.query.all()
    return render_template("mainte/users/index.html", users=users)

# ユーザー新規登録画面
@mainte.route("/users/create", methods=["GET", "POST"])
def users_create():
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("mainte.users_index"))
    return render_template("mainte/users/create.html", form=form)

# ユーザー更新画面
@mainte.route("/users/<user_id>", methods=["GET", "POST"])
def users_update(user_id):
    form = UserForm()
    # ユーザー情報をDBから取得
    user = User.query.filter_by(id=user_id).first()

    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("mainte.users_index"))
    return render_template("mainte/users/update.html", form=form, user=user)

# ユーザー削除機能
@mainte.route("/users/<user_id>/delete", methods=["GET"])
def users_delete(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("mainte.users_index"))

webapp/mainte/templates/mainte/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
        <link rel="stylesheet" href="{{ url_for('mainte.static', filename='css/style.css') }}" />
    </head>

    <body>
        <section class="container">
            {% block content %}{% endblock %}
        </section>
    </body>
</html>

webapp/mainte/templates/mainte/index.html
{% extends "mainte/base.html" %}
{% block title %}マスタメンテナンスメニュー{% endblock %}
{% block content %}
<h2>マスタメンテナンスメニュー</h2>

<ul class="nav flex-column">
    <li><a href="{{ url_for('mainte.users_index') }}" class="btn btn-primary">ユーザーマスタ</a></li>
</ul>
{% endblock %}

webapp/mainte/templates/mainte/users/create.html
{% extends "mainte/base.html" %}
{% block title %}ユーザー新規登録{% endblock %}
{% block content %}
<h3>ユーザー新規登録</h3>

<form action="{{ url_for('mainte.users_create') }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    {{ form.username.label }} {{ form.username(size=15, class="form-control is-invalid mm-input", placeholder="ユーザー名") }}
    {% for error in form.username.errors %}
        <div class="invalid-feedback">{{ error }}</div>
    {% endfor %}
    {{ form.email.label }} {{ form.email(size=30, class="form-control is-invalid mm-input", placeholder="メールアドレス") }}
    {% for error in form.email.errors %}
        <div class="invalid-feedback">{{ error }}</div>
    {% endfor %}
    {{ form.password.label }} {{ form.password(size=15, class="form-control is-invalid mm-input", placeholder="パスワード") }}
    {% for error in form.password.errors %}
        <div class="invalid-feedback">{{ error }}</div>
    {% endfor %}
    {{ form.submit(class="btn btn-md btn-primary mm-btn") }}
    <a href="{{ url_for('mainte.users_index') }}" class="btn btn-primary mm-btn">戻る</a>
</form>
{% endblock %}

webapp/mainte/templates/mainte/users/index.html
{% extends "mainte/base.html" %}
{% block title %}ユーザー一覧{% endblock %}
{% block content %}
<h3>ユーザー一覧</h3>

<div class="text-left mt-3">
    <a href="{{ url_for('mainte.users_create') }}" class="btn btn-primary">新規作成</a>
    <a href="{{ url_for('mainte.index') }}" class="btn btn-primary">戻る</a>
</div>

<div class="mt-4">
    <table class="table">
        <tr>            
            <th>ID</th>
            <th>ユーザー名</th>
            <th>メールアドレス</th>
            <th>操作</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td><a href="{{ url_for('mainte.users_update', user_id=user.id) }}" class="btn btn-primary">更新</a>
                <a href="{{ url_for('mainte.users_delete', user_id=user.id) }}" class="btn btn-primary">削除</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

webapp/mainte/templates/mainte/users/update.html
{% extends "mainte/base.html" %}
{% block title %}ユーザー更新{% endblock %}
{% block content %}
<h3>ユーザー更新</h3>

<form action="{{ url_for('mainte.users_update', user_id=user.id) }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    {{ form.username.label }} {{ form.username(size=15, class="form-control is-invalid mm-input", placeholder="ユーザー名", value=user.username) }}
    {% for error in form.username.errors %}
        <div class="invalid-feedback">{{ error }}</div>
    {% endfor %}    
    {{ form.email.label }} {{ form.email(size=30, class="form-control is-invalid mm-input", placeholder="メールアドレス", value=user.email) }}
    {% for error in form.email.errors %}
        <div class="invalid-feedback">{{ error }}</div>
    {% endfor %}
    {{ form.password.label }} {{ form.password(size=15, class="form-control is-invalid mm-input", placeholder="パスワード") }}
    {% for error in form.password.errors %}
        <div class="invalid-feedback">{{ error }}</div>
    {% endfor %}
    <input type="submit" class="btn btn-primary mm-btn" value="更新" />
    <a href="{{ url_for('mainte.users_index') }}" class="btn btn-primary mm-btn">戻る</a>
</form>
{% endblock %}