webapp/appli/views.py
from flask import Blueprint, render_template

appli = Blueprint("appli", __name__, template_folder="templates")

@appli.route("/")
def index():
    return render_template("appli/index.html")

webapp/appli/templates/appli/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
        <link rel="stylesheet" href="{{ url_for('auth.static', filename='css/style.css') }}" />
    </head>

    <body>
        <!-- ナビゲーションバーを作成する -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('appli.index') }}">ai</a>
                <ul class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <!-- ログインしている場合 -->
                        <li class="nav-item">
                            <span class="nav-link">{{ current_user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">ログアウト</a>
                        </li>
                    {% else %}
                        <!-- ログインしていない場合 -->
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <section class="container">
            {% block content %}{% endblock %}
        </section>
    </body>
</html>

webapp/appli/templates/appli/index.html
{% extends "appli/base.html" %}
{% block title %}ＡＩアプリ{% endblock %}
{% block content %}
<h2>ＡＩアプリ</h2>

{% endblock %}